services:
  db:
    image: postgres
    container_name: postgres_ecommerce_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ecommercedb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  ms-users:
    build: ./ms-users
    container_name: ms_users_service
    depends_on:
      - db
    ports:
      - "3001:3001"
    env_file:
      - ./ms-users/.env.prod

  ms-orders:
    build: ./ms-orders
    container_name: ms_orders_service
    depends_on:
      - db
      - kafka
    ports:
      - "3002:3002"
    env_file:
      - ./ms-orders/.env.prod

  ms-notifications:
    build: ./ms-notifications
    container_name: ms_notifications_service
    depends_on:
      - kafka
      - db
    ports:
      - "3003:3003"
    env_file:
      - ./ms-notifications/.env.prod

  api-gateway:
    build: ./api-gateway
    container_name: api_gateway_service
    depends_on:
      - ms-users
    env_file:
      - ./api-gateway/.env.prod
    ports:
      - "3000:3000"

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
    volumes:
      - ./_data/zookeeper/data:/data
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    hostname: kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: LISTENER_DOCKER_INTERNAL://:19092,LISTENER_DOCKER_EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: __consumer_offsets:50:1,order-created:1:1
    volumes:
      - ./_data/kafka/data:/var/lib/kafka/data
    depends_on:
      - zookeeper
networks:
  elastic:
    driver: bridge
